### ISSUE TITLE
Run gherkin-testcafe package in docker image

### ISSUE THREAD

**Issue by raj-balaebail** [Arthy000/gherkin-testcafe#41]
Trying to get gherkin-testcafe working in the docker image. Is there documentation on how to get gherkin-testcafe working in a container ?

**Comment by raj-balaebail** [comment]
FWIW, I do see that it can be done in an older commit. 
https://github.com/Arthy000/gherkin-testcafe/commit/0d8c38c24960858d8cf3380ffcd5dfb10cbc835d#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

**Comment by raj-balaebail** [comment]
FWIW, I solved this based on the deprecated docker support.

**Comment by Arthy000** [comment]
Sorry I didn't reply sooner, but I have very little experience with Docker anyway, I'll have to work on that one day. Can I close this issue or do you need something else?

**Comment by raj-balaebail** [comment]
Feel free to close out the issue. I was in a similar boat with docker anyway. For posterity, for folks who want to see how I solved the issue, I got the package working with two different docker files. One building everything from scratch (based on the deprecated example) and one from the default rc image of TestCafe.

From Scratch :
```
FROM node:alpine as builder

RUN yarn add gherkin-testcafe
RUN mv /node_modules/gherkin-testcafe/package.json /package.json
RUN yarn install

FROM alpine:edge

ENV ALPINE_REPOS="\
 --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/\
 --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/\
 --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/\
 --repository http://dl-cdn.alpinelinux.org/alpine/v3.11/community/\
 --repository http://dl-cdn.alpinelinux.org/alpine/v3.11/main/\
"

RUN apk --no-cache $ALPINE_REPOS upgrade && \
 apk --no-cache $ALPINE_REPOS add \
 libevent nodejs npm chromium firefox xwininfo xvfb dbus eudev ttf-freefont fluxbox procps tzdata

//I needed this library for my suite. This line can be deleted if the library isn't used.
RUN npm install axios

RUN git clone https://github.com/Arthy000/gherkin-testcafe.git /test
RUN mv /test/build/docker/test.sh /test/test.sh

COPY --from=builder /node_modules /test/node_modules

WORKDIR /test
RUN chmod +x ./test.sh && ln -s /test/test.sh /usr/local/bin/gherkin-testcafe

CMD tail -f /dev/null
```

From testcafe:rc image:
```
FROM node:alpine as builder
RUN yarn add gherkin-testcafe
RUN mv /node_modules/gherkin-testcafe/package.json /package.json
RUN yarn install

FROM docker.artifactory.internal.amount.com/testcafe/testcafe:rc

USER root

//I needed this library for my suite. This line can be deleted if the library isn't used.
RUN npm install axios

RUN apk add --no-cache git
RUN apk add --no-cache openssh
RUN git clone https://github.com/Arthy000/gherkin-testcafe.git /test
RUN mv /test/build/docker/test.sh /test/test.sh

COPY --from=builder /node_modules /node_modules

WORKDIR /test
RUN chmod +x ./test.sh && ln -s /test/test.sh /usr/local/bin/gherkin-testcafe

CMD tail -f /dev/null
```

**Comment by s0leris** [comment]
@raj-balaebail which docker commands did you use to build the image above and run tests on docker please. 
(Sorry I have little experience in docker myself)
Also is cloning the repo really needed?

**Comment by raj-balaebail** [comment]
@s0leris I built the container in my test suite repository. My (simplified) directory structure is:

- e2e-tests
  - testcafe
    - page-objects
    - screenshots
    - step-definitions
    - test-features
  - .testcaferc.json
  - docker-compose-cucumber.yml
  - DockerfileCucumber

My docker-compose-cucumber.yml file looks like:
```
version: '3'

services:
  testcafe-cucumber:
    build:
      context: .
      dockerfile: DockerfileCucumber
    container_name: testcafe-cucumber
    volumes:
      - ./.testcaferc.json:/test/.testcaferc.json
      - ./testcafe:/testcafe
      - ./testcafe/screenshots:/test/screenshots

    entrypoint: "/test/test.sh chromium ${FILES_TO_RUN:-/testcafe/**/*.js /testcafe/**/*.feature}"
    environment:
      - PARTNER_ENVIRONMENT=${PARTNER_ENVIRONMENT}
    user: root
```
Note in the above code, the env vars (`FILES_TO_RUN` and `PARTNER_ENVIRONMENT`) are needed for my tests. The DockerCucumber file is the one attached above under testcafe:rc image.

I run the tests in docker using:
`docker-compose -f docker-compose-cucumber.yml run testcafe-cucumber`

In theory, you could have a step where you build this container from the root directory of gherkin-testcafe package. That would mean a number of these commands would need to be tweaked, but doing so also means you wouldn't have to clone the repo as I did in ```RUN git clone https://github.com/Arthy000/gherkin-testcafe.git /test```
